image : $IMAGE

stages:
  - build_releases

build_windows:
 stage: build_releases
 before_script:
  - 'ls -lah'
  - 'cd Ionburst.Apps.IonFS'
  - 'dotnet restore -s https://api.nuget.org/v3/index.json'
 script:
  - 'dotnet build -c Release -p:AssemblyVersion=$VERSION -p:PackageVersion=$VERSION'
  - 'dotnet publish -c Release -p:AssemblyVersion=$VERSION -p:PackageVersion=$VERSION -p:PublishSingleFile=true -p:PublishTrimmed=true --runtime win-x64'
  - 'cp -R bin/Release/netcoreapp3.1/win-x64/publish .'
  - 'ls -lah'
  - 'pwd'
 when: manual
 allow_failure: false
 artifacts:
  paths:
  - /builds/ionburst/ionfs/Ionburst.Apps.IonFS/publish/
  name: "$CI_PROJECT_NAME-$VERSION-windows"
  when: on_success
 only:
  - master

build_mac:
 stage: build_releases
 before_script:
  - 'ls -lah'
  - 'cd Ionburst.Apps.IonFS'
  - 'dotnet restore -s https://api.nuget.org/v3/index.json'
 script:
  - 'dotnet build -c Release -p:AssemblyVersion=$VERSION -p:PackageVersion=$VERSION'
  - 'dotnet publish -c Release -p:AssemblyVersion=$VERSION -p:PackageVersion=$VERSION -p:PublishSingleFile=true -p:PublishTrimmed=true --runtime osx-x64'
  - 'cp -R bin/Release/netcoreapp3.1/osx-x64/publish .'
  - 'ls -lah'
  - 'pwd'
 when: manual
 allow_failure: false
 artifacts:
  paths:
  - /builds/ionburst/ionfs/Ionburst.Apps.IonFS/publish/
  name: "$CI_PROJECT_NAME-$VERSION-mac"
  when: on_success
 only:
  - master
  
build_linux:
 stage: build_releases
 before_script:
  - 'ls -lah'
  - 'cd Ionburst.Apps.IonFS'
  - 'dotnet restore -s https://api.nuget.org/v3/index.json'
 script:
  - 'dotnet build -c Release -p:AssemblyVersion=$VERSION -p:PackageVersion=$VERSION'
  - 'dotnet publish -c Release -p:AssemblyVersion=$VERSION -p:PackageVersion=$VERSION -p:PublishSingleFile=true -p:PublishTrimmed=true --runtime linux-x64'
  - 'cp -R bin/Release/netcoreapp3.1/linux-x64/publish .'
  - 'ls -lah'
  - 'pwd'
 when: manual
 allow_failure: false
 artifacts:
  paths:
  - /builds/ionburst/ionfs/Ionburst.Apps.IonFS/publish/
  name: "$CI_PROJECT_NAME-$VERSION-linux"
  when: on_success
 only:
  - master
